### ISSUE TITLE
MIT license conflicting with website terms of use https://rxn.res.ibm.com/ 

### ISSUE THREAD

**Issue by gtteixeira** [rxn4chemistry/rxn4chemistry#20]
I have a doubt whether the terms of use for the MIT license would be in conflict with the terms of use for the system available on the website https://rxn.res.ibm.com/, since the library is a wrapper of the same . The website's terms of use state that:

_"The use authorized under this agreement is non-commercial in nature (e.g., you may not sell the content you access on or through this Web site.) All other use of this site is prohibited. Except for the limited permission in the preceding paragraph, IBM does not grant you any express or implied rights or licenses under any patents, trademarks, copyrights, or other proprietary or intellectual property rights. You may not mirror any of the content from this site on another Web site or in any other media.Any software and other materials that are made available for downloading, access, or other use from this site with their own license terms will be governed by such terms, conditions, and notices. comply with such terms or any of the terms on this site will result in automatic termination of any rights granted to you, without prior notice, and you must immediately destroy all copies of downloaded materials in your possession, custody or control. "_

That is, since the library downloads material via the site's API, if it has denied the right to use it in another application, the library cannot make use of the MIT license.
I would like to ask that you please clarify this conflict.

**Comment by drugilsberg** [comment]
Hi @gtteixeira,

thanks a lot for the interest in our work and in the RXN for Chemistry service.

The MIT license refers to the source code of the wrapper implemented in this repository.

As you rightly pointed out, the services offered by the RXN For Chemistry portal and the website materials follow the IBM terms and conditions.
These terms and conditions allowed us to state since the early days that the results of the models (reaction/retrosynthesis/actions prediction results) can be downloaded and used by each user with no limitations.

It is a good time to be more explicit and specify also the license under which you can reuse the downloaded results: a CC-BY license (see the [updated terms](https://rxn.res.ibm.com/terms-of-use), now also linked in the main page).

I hope this helps you and clarify whether the `rxn4chemistry`package and our predictive models suit your needs.

**Comment by gtteixeira** [comment]
Understood.
So please, update the link to the terms of use explained on the login page. It does not yet reflect that updated link that you explained in your answer. This causes a lot of confusion.
Thanks.
![image](https://user-images.githubusercontent.com/28991408/109967057-b7e14380-7ccf-11eb-8598-fa2fe1c20e54.png)

**Comment by drugilsberg** [comment]
Hi @gtteixeira the link should be up-to-date also on the login page, could please try to refresh the cache of the browser used?

**Comment by gtteixeira** [comment]
Hi drugilsberg

I have checked now and it is ok. Despite yesterday I tried many times refreshing the browser without succsess. Until there it was not reflecting the changes.
Thanks for your help again.

**Comment by drugilsberg** [comment]
HI @gtteixeira thanks a lot to you for reporting this, closing  the issue :)
