### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by pythonnewbie3** [rxn4chemistry/rxn4chemistry#27]
When I run the different examples from the documentations I alway get errors.  For example this one:

_

> api_key = 'api_key'
> from rxn4chemistry import RXN4ChemistryWrapper
> 
> rxn4chemistry_wrapper = RXN4ChemistryWrapper(api_key=api_key)
> # NOTE: you can create a project or set an esiting one using:
> # rxn4chemistry_wrapper.set_project('PROJECT_ID')
> rxn4chemistry_wrapper.create_project('test_wrapper')
> 
> results = rxn4chemistry_wrapper.paragraph_to_actions(
>     'To a stirred solution of '
>     '7-(difluoromethylsulfonyl)-4-fluoro-indan-1-one (110 mg, '
>     '0.42 mmol) in methanol (4 mL) was added sodium borohydride '
>     '(24 mg, 0.62 mmol). The reaction mixture was stirred at '
>     'ambient temperature for 1 hour.'
> )
> print(results['actions'])

_

gives me:

> Unexpected error.
> {"timestamp":1631892196196,"status":429,"error":"Too Many Requests","message":"Too many requests","path":"/rxn/api/api/v1/paragraph-actions"}
> Traceback (most recent call last):
> 
>   File "C:\Users\TMK\untitled0.py", line 16, in <module>
>     print(results['actions'])
> 
> KeyError: 'actions'

What can I do? I'm really interesten in trying RXN4Chemistry in python....

**Comment by avaucher** [comment]
In order to avoid overloading the server, there is a limit to the number of requests you can do per minute. Just wait a few seconds and try again, it will work. 

Whenever you see `"Too Many Requests"`, it means you should wait a little bit.

If you want to execute the notebook all at once, you can add a few `time.sleep(5)` between the requests.
