### ISSUE TITLE
The results['status'] output  is always NEW

### ISSUE THREAD

**Issue by eleven-0325** [rxn4chemistry/rxn4chemistry#42]
When I perform Retrosynthesis prediction operation, the status output is always "NEW",
something is wrong?
examples:
the results is "{'retrosynthetic_paths': [], 'status': 'NEW', 'response' ..."

**Comment by avaucher** [comment]
Hi @eleven-0325,

Which command did you execute for that? Was it something like
```python
predict_automatic_retrosynthesis_response = rxn4chemistry_wrapper.predict_automatic_retrosynthesis(product=smiles)
``` 
?

If so, this is the expected behavior. A retrosynthetic prediction takes a few minutes to complete, and the command above is the one to submit the task; it will return immediately, with the status `NEW`.  

To get the actual result, you can call another command until the status changes 
```python
predict_automatic_retrosynthesis_results = rxn4chemistry_wrapper.get_predict_automatic_retrosynthesis_results(
    predict_automatic_retrosynthesis_response['prediction_id']
)
print(predict_automatic_retrosynthesis_results['status'])
```

This [notebook](https://github.com/rxn4chemistry/rxn4chemistry/blob/main/examples/rxn4chemistry_tour.ipynb) is a good example of how this works.

Let us know if this helped!

**Comment by eleven-0325** [comment]
@avaucher Thank you very much for your answer. I have solved this problem according to your prompt.
