### ISSUE TITLE
"solved"/"not-solved" reaction outcome

### ISSUE THREAD

**Issue by palazzef** [rxn4chemistry/rxn4chemistry#53]
Hi, 

Thanks for the nice API/tool. 

It would be great to have the option to obtain the reaction prediction outcome directly from the API run. 
Basically without visually expecting each reaction in the dashboard looking for the red boxed molecules, have a label with "solved"/"not solved" (or 1/0) directly in the output of the run.

Thanks again.

Ciao
Ferri

**Comment by drugilsberg** [comment]
Thanks @palazzef, we are working on these feature in this pull request: https://github.com/rxn4chemistry/rxn4chemistry/pull/52

**Comment by palazzef** [comment]
Great! thanks!

**Comment by drugilsberg** [comment]
Hey @palazzef we realeased a new version implementing here a method to process the retrieved results and complement them with the info on the commercial availability of the starting materials: https://github.com/rxn4chemistry/rxn4chemistry/blob/41d767ab97e6eeb322b50875fc84587f7cc44049/rxn4chemistry/utilities.py#L36.
The one I linked operates on all the trees at once and produce a small dictionary report for each, otherwise you can simply run it directly per tree using the other method.
Feel free to close the issue in case this addresses your issues.

**Comment by palazzef** [comment]
Works like a charm! Thanks!
